name = "JavaScript"
grammar = "javascript"
path_suffixes = ["js", "jsx", "mjs", "cjs"]
line_comments = ["// "]
block_comment = ["/*","*/"]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = false, newline = true, not_in = ["comment", "string"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
    { start = "`", end = "`", close = true, newline = false, not_in = ["string"] },
]
